<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcfZqR4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcfZqR4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXcfZqR4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXcfZqR4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXcfZqR4\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XcfZqR4',
    'container.build_id' => 'adb1f2a3',
    'container.build_time' => 1520699386,
));
