<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJMp6ZUv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJMp6ZUv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJMp6ZUv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJMp6ZUv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJMp6ZUv\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JMp6ZUv',
    'container.build_id' => '127a64a2',
    'container.build_time' => 1527840511,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJMp6ZUv');
