<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUuGGRQD\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUuGGRQD/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUuGGRQD.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUuGGRQD\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUuGGRQD\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UuGGRQD',
    'container.build_id' => '96c675c0',
    'container.build_time' => 1526752998,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUuGGRQD');
