<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tache extends \App\Entity\Tache implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'Titre_Tache', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'Value_Tache', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'Pers_Tache', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'Desc_Tache', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'goal'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'Titre_Tache', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'Value_Tache', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'Pers_Tache', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'Desc_Tache', '' . "\0" . 'App\\Entity\\Tache' . "\0" . 'goal'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tache $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getid', []);

        return parent::getid();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreTache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreTache', []);

        return parent::getTitreTache();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreTache($Titre_Tache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreTache', [$Titre_Tache]);

        return parent::setTitreTache($Titre_Tache);
    }

    /**
     * {@inheritDoc}
     */
    public function getValueTache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueTache', []);

        return parent::getValueTache();
    }

    /**
     * {@inheritDoc}
     */
    public function setValueTache($Value_Tache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValueTache', [$Value_Tache]);

        return parent::setValueTache($Value_Tache);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersTache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersTache', []);

        return parent::getPersTache();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersTache($Pers_Tache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersTache', [$Pers_Tache]);

        return parent::setPersTache($Pers_Tache);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescTache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescTache', []);

        return parent::getDescTache();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescTache($Desc_Tache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescTache', [$Desc_Tache]);

        return parent::setDescTache($Desc_Tache);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoal(): \App\Entity\Goal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoal', []);

        return parent::getGoal();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoal(\App\Entity\Goal $goal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoal', [$goal]);

        return parent::setGoal($goal);
    }

}
